### ISSUE TITLE
[Docs] create a latest-version-docs redirect

### ISSUE THREAD

**Issue by make-github-pseudonymous-again** [jspm/jspm.org#1]
Currently https://jspm.org/docs errors with a `403`. Would be nice if one of those would redirect to the current stable version:
  - https://jspm.org/docs
  - https://jspm.org/docs/stable
  - https://jspm.org/docs/latest

There could also be a version lister at https://jspm.org/docs.

Could also add a redirect for beta versions (https://jspm.org/docs/beta).

**Comment by guybedford** [comment]
This is supported in the upcoming version.
