### ISSUE TITLE
ga.system.jspm.io certificate expired

### ISSUE THREAD

**Issue by GeeWizWow** [jspm/jspm.org#13]
Hi, the certificate for test.jspm.io with the SANs

* test.jspm.io
* ga.jspm.io
* ga.system.jspm.io

Expired ~ half an hour ago, essentially causing an outage. Anyone with publishing permissions able to check this out?

Thanks

**Comment by guybedford** [comment]
@GeeWizWow this is currently only affecting `ga.system.jspm.io`, was this how you noticed the issue? Thank you for the report, I'm looking into the fix now and should be able to resolve it shortly.

**Comment by GeeWizWow** [comment]
@guybedford Thanks.

To answer your question, It is, yes. 

I'm currently online in your discord channel, same name as here, feel free to reach out there if you want to carry on this discussion.

**Comment by guybedford** [comment]
@GeeWizWow should be back up now - it was the last server still on the old CDN infrastructure, so everything is using Cloudfront edge functions now. Thanks for the ping on this.

**Comment by GeeWizWow** [comment]
Awesome, good to hear! Thanks for the quick resolve on this, appreciate it.
