### ISSUE TITLE
Cannot Access Website from the UK

### ISSUE THREAD

**Issue by aloisklink** [jspm/jspm.org#2]
CloudFlare is printing out the following screen:

![image](https://user-images.githubusercontent.com/19716675/44526649-99506980-a6dc-11e8-8c5b-2ca736a65b1b.png)

I've tested on a mobile network, as well as my home network, and they both are returning the same thing.

The UK site, <http://isitdown.co.uk/> reports that <https://jspm.org> is returning an error code 522, but all the other is it down websites are returning successes, but that might only be because they see the CloudFlare error page and think that is valid.

**Comment by guybedford** [comment]
Thanks for posting - it should be working now.

**Comment by aloisklink** [comment]
Damn, that was fast! Yep, it's fixed now. Thanks for the help.
