### ISSUE TITLE
Cloudflare Error 526: Invalid SSL certificate

### ISSUE THREAD

**Issue by aloisklink** [jspm/jspm.org#3]
Hi @guybedford, sorry to bother you again.

<https://jspm.org/> is down for me, with Cloudflare giving the error:

**Error 526**
Ray ID: 4567be917891bc0e • 2018-09-07 08:18:23 UTC
**Invalid SSL certificate**

![image](https://user-images.githubusercontent.com/19716675/45207220-5adfb080-b27f-11e8-948d-4a715920449d.png)

If you are using a Symantec SSL certificate, Cloudflare might be blocking it, since all the major browsers are about to distrust it.

**Comment by guybedford** [comment]
Thanks very much for posting - this should be working now!
