### ISSUE TITLE
import url scopes get filtered out by email protection

### ISSUE THREAD

**Issue by make-github-pseudonymous-again** [jspm/jspm.org#9]
![2020-09-02-175321_1141x430](https://user-images.githubusercontent.com/5165674/92006833-8352f600-ed45-11ea-9e49-05f663d244c8.png)

Scopes are proudly protected by Cloudflare's advanced email classification technology!

![2020-09-02-175633_1470x509](https://user-images.githubusercontent.com/5165674/92006997-abdaf000-ed45-11ea-9d54-472b2667c5f6.png)

**Comment by guybedford** [comment]
It looks like this is a bug in Cloudflares email obfuscation as they claim it does not apply within script tags. See eg https://support.cloudflare.com/hc/en-us/articles/200170016-What-is-Email-Address-Obfuscation-

I'd suggest disabling the cloudflare feature, following up with them further, or disabling as per the instructions in the link above.

**Comment by guybedford** [comment]
Also are you seeing this on the jspm website itself? The website doesn't have any HTML rewrites enabled and I can't replicate that.

**Comment by make-github-pseudonymous-again** [comment]
> Also are you seeing this on the jspm website itself? The website doesn't have any HTML rewrites enabled and I can't replicate that.

Yes on https://jspm.org.

I am disabling JavaScript by default with NoScript. If I enable JavaScript the package scopes names are not filtered out.

**Comment by guybedford** [comment]
Wow, I did not even realise that feature was being applied. Disabled, thanks!
